sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t kunwarf/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kunwarf/react-test npm test

after_success:
  - docker build -t kunwarf/multi-client ./client
  - docker build -t kunwarf/multi-nginx ./nginx
  - docker build -t kunwarf/multi-server ./server
  - docker build -t kunwarf/multi-worker ./worker
  # Log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push kunwarf/multi-client
  - docker push kunwarf/multi-nginx
  - docker push kunwarf/multi-server
  - docker push kunwarf/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Multi-Docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-133903928003"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY
